package com.xym.bossed.ws.implement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.xym.bossed.ws.interfaces.IKehuWebService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-08-01T13:11:19.250+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "KehuService", 
                  wsdlLocation = "http://localhost:8080/bossedPlug/ws/kehuws?wsdl",
                  targetNamespace = "http://implement.ws.bossed.xym.com/") 
public class KehuService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://implement.ws.bossed.xym.com/", "KehuService");
    public final static QName KehuWebServicePort = new QName("http://implement.ws.bossed.xym.com/", "KehuWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/bossedPlug/ws/kehuws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KehuService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/bossedPlug/ws/kehuws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KehuService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KehuService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KehuService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KehuService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KehuService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KehuService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IKehuWebService
     */
    @WebEndpoint(name = "KehuWebServicePort")
    public IKehuWebService getKehuWebServicePort() {
        return super.getPort(KehuWebServicePort, IKehuWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IKehuWebService
     */
    @WebEndpoint(name = "KehuWebServicePort")
    public IKehuWebService getKehuWebServicePort(WebServiceFeature... features) {
        return super.getPort(KehuWebServicePort, IKehuWebService.class, features);
    }

}
